### PR TITLE
Jemmings git patch 1

### PR DESCRIPTION
**Pull request by jemmings-git**
This is a modification of the stromatolites demo. We have defined our own terms such as 'pyrite framboid' for GDD extraction.

### CODE REVIEW

**Comment by jemmings-git** [comment]
Do we need to define the input bibliography or is this something the GDD team define for us?

Any advise appreciated @iross

**Comment by iross** [comment]
Hello! The typical workflow is that you define some kind of input corpus, typically by defining a list of terms of interest. I'll put together a small set of our data outputs from some of the documents within the corpus that include things you might be interested. At that point, you're free to develop however you want. When you're done developing, I'll deploy it on the full relevant corpus. Since you're using this application as a basis, it's already in a working state, so I'll go ahead and deploy it on the set of documents matching the terms in https://github.com/jemmings-git/stromatolites_demo/pull/2/files#diff-98799c9f884eec29fde912c4a170d79e

**Comment by metazool** [comment]
Thank you very much for following this up from the GDD end @iross - let us know what is the best way to pick up the results of an initial trial run from you. We're hoping to spend some time on understanding and refining the output next week...

**Comment by jemmings-git** [comment]
Many thanks for the support @iross , very much appreciated

**Comment by iross** [comment]
Hi --
I've put the results from https://geodeepdive.org/app_output/jemmings_9Jul2019.zip.

Feel free to send me an email with any follow-up questions you may have.

**Comment by metazool** [comment]
Thank you so much for this @iross it is perfect timing

**Comment by jemmings-git** [comment]
This is fantastic, many thanks @iross - we will keep you updated regarding the analysis & next steps.

**Comment by jemmings-git** [comment]
Hi @iross we have completed our analysis of the test outputs you kindly provided us earlier this month. We now request this (jemmings-git-patch-1) to be run against the full GDD infrastructure. Is this OK?

This program is unchanged since testing. Any help would be appreciated.

@metazool

**Comment by iross** [comment]
The results I passed along were the output of running the application
against all of the ~30,000 documents that mention any of the terms of
interest (obtained from the `terms_included` file). We can alter the logic
of what makes a document worth investigating, but because the logic of the
app itself requires at least one of those terms, it's should be the
complete set of output-producing documents.

**Comment by jemmings-git** [comment]
Many thanks for the clarification, @iross . In this case we will continue with our analysis. Do you know it might be possible for us to access the raw xDD output (the parsed sentences, but not the full text)? This will help us understand the dataset & reproducibility.

**Comment by jemmings-git** [comment]
Hi @iross - are you able to provide us with the reference list for the docid's listed in results.csv?

.txt .csv or similar format would be ideal.

We will need to compile the reference list ahead of submission for publication. We will involve you in this process, as co-author(s) if preferable. I will circulate the manuscript to all co-workers as soon as possible. The reference list is also important because we wish to manually assess a subset of the output (replicating the Peters et al. 2017 stromatolites workflow - in order to estimate/verify accuracy of the method). 

Any help would be appreciated. @metazool

**Comment by iross** [comment]
Sure! I'll pass that along tomorrow.

**Comment by iross** [comment]
Hi--
I dumped the references here:
http://geodeepdive.org/app_output/jemmings_references.zip

Feel free to reach out to me via email (iross at cs dot wisc dot edu) if you have any questions -- it's a bit more appropriate here than keeping up a chain on this github issue.

**Pull request merged**
